### ISSUE TITLE
Worldgen issues when used alongside TerraBlender

### ISSUE THREAD

**Issue by TheTrueYak** [BackupCup/hexed#5]
Having Hexed installed alongside mods that use TerraBlender for biome worldgen results in weird patches of placeholder biomes called biome.terrablender.deferred_placeholder. (shown in the image) I found this when using Hexed alongside [Surface](https://modrinth.com/mod/surface), but because the bugged biome is marked as TerraBlender's, I assume it happens with all TerraBlender-based worldgen. This was also tested in a bare instance (Fabric API 0.92.1+1.20.1, Fabric Language Kotlin 1.10.20+kotlin.1.9.24, Hexed 0.8.1H+MC1.20.1, Surface 1.8.1-1.20.1, and TerraBlender 3.0.1.6 for Fabric 1.20.1), and was still bugged. 

The generation in question:
![2024-05-19_15 04 09](https://github.com/BackupCup/hexed/assets/107325508/a69674d4-70d1-46e4-b735-bb6f4f1719c9)

**Comment by BackupCup** [comment]
Seems as the Biolith package still interferes with TerraBlender reliant mods. This is fixed in the dev version currently (just, removing Biolith from dependencies basically)

**Comment by TheTrueYak** [comment]
Compiled the dev version (0.8.3) and it works perfectly, thank you!

**Comment by TheTrueYak** [comment]
Nevermind I'm a huge dumbass and I've had Surface disabled for the last 2 days, this bug still persists with Hexed 0.8.3, Surface 1.8.1-1.20.1, and Terrablender 3.0.1.6 (bare instance)

**Comment by BackupCup** [comment]
Yep, this is for sure Biolith conflicting with Terrablender. Again, it's gonna be fixed in the next release version.
